/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apphibernatedumitru;

import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

/**
 *
 * @author DAM2A-28
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    
    
        //Para crear una sesión llamamos al método getSessionFactory()
        SessionFactory sesion = SessionFactoryUtil.getSessionFactory();

        //Para abrir la sesión llamamos al método openSession().
        Session session = sesion.openSession();

        /*
        Para insertar, borrar o modificar una fila en la tabla hay que abrir una
        transacción.
        Para abrir una transacción utilizamos el método beginTransaction()
         */
        Transaction transaction = session.beginTransaction();
        //indica el comienzo de una transacción.
    
    public Formulario() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnInsertar = new javax.swing.JButton();
        btnModificarDestino = new javax.swing.JButton();
        btnBorrarVuelo = new javax.swing.JButton();
        btnConsultaVuelos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnModificarDestino.setText("Modifica destino");
        btnModificarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDestinoActionPerformed(evt);
            }
        });

        btnBorrarVuelo.setText("Borra un vuelo");
        btnBorrarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarVueloActionPerformed(evt);
            }
        });

        btnConsultaVuelos.setText("Consulta vuelos");
        btnConsultaVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaVuelosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBorrarVuelo)
                            .addComponent(btnInsertar))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarDestino)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnConsultaVuelos)
                                .addGap(3, 3, 3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnModificarDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarVuelo)
                    .addComponent(btnConsultaVuelos))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        frmInsertar insertar = new frmInsertar();
        insertar.setVisible(true);
        
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDestinoActionPerformed
        frmModificarDestino modDestino = new frmModificarDestino();
        modDestino.setVisible(true);
    }//GEN-LAST:event_btnModificarDestinoActionPerformed

    private void btnBorrarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarVueloActionPerformed
        String codigoVueloIntroducido = JOptionPane.showInputDialog("Introduce el numero del vuelo");
        
        if (JOptionPane.showConfirmDialog(this, "¿Seguro que quieres borrarlo?") == 0) {
            Vuelos vuelo = (Vuelos) session.load(Vuelos.class, (String) codigoVueloIntroducido);
            session.delete(vuelo);
            transaction.commit();
            session.close();
            
            JOptionPane.showMessageDialog(this, "Vuelo borrado");
            
        } else {
            JOptionPane.showMessageDialog(this, "Has cancelado el borrado");
        }
        
       
        
    }//GEN-LAST:event_btnBorrarVueloActionPerformed

    private void btnConsultaVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaVuelosActionPerformed
        
        Vuelos vuelo = new Vuelos();
        Query q = session.createQuery("from Vuelos");
        List<Vuelos> listaVuelo = q.list();
        Iterator<Vuelos> iter = listaVuelo.iterator();
        while (iter.hasNext()) {
            vuelo = (Vuelos) iter.next();
            
            txtArea.append("PROCEDENCIA: " + vuelo.getProcedencia() + "\n");
            txtArea.append("DESTINO: " + vuelo.getDestino() + "\n");
            txtArea.append("HORA DE SALIDA: " + vuelo.getHoraSalida() + "\n");
        }
        session.close();
    }//GEN-LAST:event_btnConsultaVuelosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarVuelo;
    private javax.swing.JButton btnConsultaVuelos;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificarDestino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
